---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Сайт должен иметь мобильную версию.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - На странице товара и в каталоге должны выводиться название, рейтинг, цена со скидкой и без. 
  - Пользователь должен иметь возможность товар в корзину и продолжить выбирать товары в каталоге.
  - На странице корзины пользователь должен иметь возможность удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
  - Веб-сайт магазина должен быть реализован как SPA приложение.
implicit:
  - Страницы каталога должны быть пронумерованы.
  - При переходе сайта на русский язык стоимость товаров в каталоге должна быть отображена в RUB (по обменному курсу на день открытия сайта).
  - После оформлении заказа корзина должна быть очищена от добавленных ранее товаров.
  - В фильтре Цена должна быть установлена минимальная граница параметра "До" 0. Цена не может быть отрицательной.
  - После оформления заказа пользователю должны быть предложены способы оплаты заказа с дальнейшим редиректом на платежный терминал
